name: Build Cloud Image

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+\-cloud\-rc[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+\-cloud\-b[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+\-cloud'
      - '[0-9]+.[0-9]+\-cloud\-rc[0-9]+'
      - '[0-9]+.[0-9]+\-cloud\-b[0-9]+'
      - '[0-9]+.[0-9]+\-cloud'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}  # checkout current branch
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build ${{ github.ref_name }} Prod Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: papermerge/papermerge:${{ github.ref_name }}
          file: docker/cloud/Dockerfile
          platforms: linux/amd64
