name: Publish to ghcr.io

on:
  workflow_dispatch:
    inputs:
      VERSION:
        required: true
        type: string
      IS_LATEST:
        type: string
        default: false
  workflow_call:
    secrets:
      MY_GH_TOKEN:
        required: true
    inputs:
      VERSION:
        required: true
        type: string
      IS_LATEST:
        type: string
        default: false

permissions:
  contents: read

jobs:
  publish-to-ghcr:
    name: Publish to ghcr.io
    runs-on: ubuntu-latest
    env:
      papermerge_image: ghcr.io/papermerge/papermerge
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GH_TOKEN }}
      - name: Build and push ${{ inputs.VERSION }}
        uses: docker/build-push-action@v3
        with:
          push: true
          tags:  ${{ env.papermerge_image }}:${{ inputs.VERSION }}
          file: docker/prod/Dockerfile
      - name: Build and push latest-headless
        uses: docker/build-push-action@v3
        with:
          push: true
          tags:  ${{ env.papermerge_image }}:latest-headless
          file: docker/prod/Dockerfile
        if: ${{ input.IS_LATEST }}
