name: Update OpenAPI Schema

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      PAPERMERGE__MAIN__SECRET_KEY:
        required: true
      GH_PAT_GENERATE_OPENAPI_SCHEMA:
        required: true

jobs:
  create-pr:
    runs-on: ubuntu-latest
    env:
      PAPERMERGE__MAIN__SECRET_KEY: ${{ secrets.PAPERMERGE__MAIN__SECRET_KEY }}
      PAPERMERGE__SEARCH__ENGINE: whoosh
      DJANGO_SETTINGS_MODULE: config.settings
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          path: main
          ref: master

      - name: Checkout openapi schema
        uses: actions/checkout@v3
        with:
          repository: papermerge/openapi-schema
          path: openapi-schema

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd main
          poetry install
          cd docker/dev
          poetry run task spectacular > ../../../openapi-schema/openapi-schema.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        id: cpr
        with:
          add-paths: openapi-schema.yaml
          path: openapi-schema
          labels: automerge
          token: ${{ secrets.GH_PAT_GENERATE_OPENAPI_SCHEMA }}

      - name: Automatically Merge PR
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: KeisukeYamashita/auto-pull-request-merge@v1
        with:
          intervalSeconds: 10
          timeoutSeconds: 30
          labels: automerge
          repository: papermerge/openapi-schema
          pullRequestNumber: ${{ steps.cpr.outputs.pull-request-number }}
          token: ${{ secrets.GH_PAT_GENERATE_OPENAPI_SCHEMA }}
          checkStatus: false

  # https://github.com/orgs/community/discussions/26323
  dispatch-event:  # trigger REST API clients generation
    needs: [ create-pr ]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger dispatch event
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PAT_GENERATE_OPENAPI_SCHEMA }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'papermerge',
              repo: 'rest-api-clients',
              workflow_id: 'generate.yml',
              ref: 'master'
            })
